Перевод Саудовской Аравии и правка названий провинций
vryzhenkin/r56-ru-loc pull request #4
Opened 2022-07-09 12:59 UTC by Laucer7

2022-07-09 13:16 UTC, vryzhenkin requested changes

2022-07-09 13:16 UTC, vryzhenkin commented on localisation/state_names_l_russian.yml
> + STATE_892:0 "Южная Ютландия"
STATE_892:0 "Northern Schleswig"
From original mod inside Steam by July 2022

2022-07-09 13:45 UTC, Laucer7 commented on localisation/state_names_l_russian.yml
> + STATE_892:0 "Южная Ютландия"
Сомнительная правка. Я понимаю, что у них, может и так. Но этот регион в составе Дании и называется Южной Ютландией. А для Германии есть ивент с переименованием.
![image](https://user-images.githubusercontent.com/38085008/178108467-f7b94c7e-6cab-4bff-903c-b93ad48e4ed0.png)

2022-07-09 13:48 UTC, vryzhenkin commented on localisation/state_names_l_russian.yml
> + STATE_892:0 "Южная Ютландия"
Вы, вероятно, правы.

2022-07-09 13:50 UTC, vryzhenkin commented on localisation/state_names_l_russian.yml
> + STATE_892:0 "Южная Ютландия"
@Laucer7 укажите, пожалуйста, ваш стим-линк в тушке пулл-реквеста. Будет нужен, когда буду обновлять мод в стиме, чтобы указать, кто принимал участие :)

2022-07-09 13:51 UTC, vryzhenkin approved these changes

2022-07-09 13:53 UTC, Laucer7 commented on localisation/state_names_l_russian.yml
> + STATE_892:0 "Южная Ютландия"
Я бы предпочел не светить свой профиль. Можете просто указать ник, без ссылок.

2022-07-09 13:57 UTC, vryzhenkin commented on localisation/state_names_l_russian.yml
> + STATE_892:0 "Южная Ютландия"
Добро. Чисто на всякий случай спрошу про скриншот - это уже с фиксом, да? 
Я просто еще обнаружил, что 
 STATE_827:0 "Южная Ютландия" все-таки присутствует под другим номером.

2022-07-10 00:36 UTC, vryzhenkin commented on localisation/state_names_l_russian.yml
> + STATE_892:0 "Южная Ютландия"
И он неверный. По 827 в текущем основном моде Кабардино-балкария..

2022-07-10 00:36 UTC, merged